### PR TITLE
fuck [], embrace █ on color

### PR DESCRIPTION
**Pull request by poggers16**

### CODE REVIEW

**Review by 5jiji — APPROVED** [review]

**Review by luihum — APPROVED** [review]

**Review by markverb1 — APPROVED** [review]
this would be better using the [on color] tags but whatever

**Review by 5jiji — APPROVED** [review]
The level limit seems good

**Review by luihum — APPROVED** [review]

**Review by 5jiji — APPROVED** [review]

**Comment by poggers16** [comment]
burning please read this

**Comment by markverb1** [comment]
he left the server and the sparrow assistant server so this project might be dead (unless a maintainer merges it without permission)

**Comment by 5jiji** [comment]
FALSE, He said i'm the new owner

**Comment by markverb1** [comment]
> FALSE, He said i'm the new owner

EPIC!!!

**Comment by poggers16** [comment]
5jiji please just merge

**Comment by markverb1** [comment]
@5jiji please actually just merge this, i will make it better later

**Comment by poggers16** [comment]
5jiji please just commit now!!!

**Comment by 5jiji** [comment]
happy now?

**Pull request merged**
